version: '3.7'
services:
  mongo:
    container_name: memapp-test-1
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: memapp-test-vol-3
        target: /data/db

volumes:
  memapp-test-vol-3:
